buildpipelinebeat:
  closeTimeout: 10
  team: defaultTeam
  status: Failure
  pipeline: fallbackPipeline
  project: fallbackProject
  error: None

# Instant push of events
queue:
  mem:
    flush.min_events: 0

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
